\doxysection{Near\+Miss\+Value\+Resolver\+Exception Class Reference}
\hypertarget{class_symfony_1_1_component_1_1_http_kernel_1_1_exception_1_1_near_miss_value_resolver_exception}{}\label{class_symfony_1_1_component_1_1_http_kernel_1_1_exception_1_1_near_miss_value_resolver_exception}\index{NearMissValueResolverException@{NearMissValueResolverException}}
Inheritance diagram for Near\+Miss\+Value\+Resolver\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{class_symfony_1_1_component_1_1_http_kernel_1_1_exception_1_1_near_miss_value_resolver_exception}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
Lets value resolvers tell when an argument could be under their watch but failed to be resolved.

Throwing this exception inside {\ttfamily Value\+Resolver\+Interface\+::resolve} does not interrupt the value resolvers chain. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
C\+:/xampp/htdocs/\+GPagos\+Ayuntamiento/vendor/symfony/http-\/kernel/\+Exception/\mbox{\hyperlink{_near_miss_value_resolver_exception_8php}{Near\+Miss\+Value\+Resolver\+Exception.\+php}}\end{DoxyCompactItemize}
